[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Import remappings are defined in remappings.txt
# Run `forge remappings > remappings.txt` to regenerate

# Compiler settings
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Enable FFI for advanced scripting (optional, use with caution)
ffi = false

# File system permissions for scripts
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# Build settings
auto_detect_remappings = true
build_info = true
extra_output = ["storageLayout"]

# Testing settings
gas_reports = ["*"]
gas_limit = 30_000_000

# Network configurations
[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
avalanche_testnet = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
avalanche_testnet = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }

# Dependency tracking (for documentation and CI)
# Note: This project uses Git submodules for now, but you can migrate to Soldeer when stable
[dependencies]
# forge-std = "1.7.6"
# openzeppelin-contracts = "5.0.2"
# openzeppelin-contracts-upgradeable = "5.0.2"

# Soldeer configuration (experimental - uncomment to enable)
# [soldeer]
# enabled = false
# remappings_generate = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
