[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# Compiler settings
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing settings
gas_reports = ["*"]
gas_limit = 30_000_000

# Network configurations
[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
avalanche_testnet = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
avalanche_testnet = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
